from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        vertical_layout = QtWidgets.QVBoxLayout(self.centralWidget)
        horizontal_layout = QtWidgets.QHBoxLayout()
        self.tableWidget = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.tableWidget.verticalHeader().setMinimumSectionSize(50)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.search_bar = QtWidgets.QLineEdit(self.centralWidget)
        self.search_bar.setObjectName("search_bar")
        self.search_bar.setMinimumSize(60, 40)
        self.add_account_button = QtWidgets.QPushButton(self.centralWidget)
        self.add_account_button.setObjectName("add_account_button")
        self.add_account_button.setMinimumSize(40, 40)
        self.add_account_button.setMaximumSize(40, 40)
        self.add_account_button.setToolTip('add an account')
        self.modify_account_button = QtWidgets.QPushButton(self.centralWidget)
        self.modify_account_button.setObjectName("modify_account_button")
        self.modify_account_button.setMinimumSize(40, 40)
        self.modify_account_button.setMaximumSize(40, 40)
        self.modify_account_button.setToolTip('modify an account')
        self.remove_account_button = QtWidgets.QPushButton(self.centralWidget)
        self.remove_account_button.setObjectName("remove_account_button")
        self.remove_account_button.setMinimumSize(40, 40)
        self.remove_account_button.setMaximumSize(40, 40)
        self.remove_account_button.setToolTip('remove an account')
        self.add_column_button = QtWidgets.QPushButton(self.centralWidget)
        self.add_column_button.setObjectName("add_column_button")
        self.add_column_button.setMinimumSize(40, 40)
        self.add_column_button.setMaximumSize(40, 40)
        self.add_column_button.setToolTip('add a column')
        self.remove_column_button = QtWidgets.QPushButton(self.centralWidget)
        self.remove_column_button.setObjectName("remove_column_button")
        self.remove_column_button.setMinimumSize(40, 40)
        self.remove_column_button.setMaximumSize(40, 40)
        self.remove_column_button.setToolTip('remove a column')
        self.reset_button = QtWidgets.QPushButton(self.centralWidget)
        self.reset_button.setObjectName("reset_button")
        self.reset_button.setMinimumSize(40, 40)
        self.reset_button.setMaximumSize(40, 40)
        self.reset_button.setToolTip('reset table')
        self.rename_column_button = QtWidgets.QPushButton(self.centralWidget)
        self.rename_column_button.setObjectName("rename_column_button")
        self.rename_column_button.setMinimumSize(40, 40)
        self.rename_column_button.setMaximumSize(40, 40)
        self.rename_column_button.setToolTip('rename a column')
        self.filter_search_button = QtWidgets.QPushButton(self.centralWidget)
        self.filter_search_button.setObjectName("filter_search_button")
        self.filter_search_button.setMinimumSize(40, 40)
        self.filter_search_button.setMaximumSize(40, 40)
        self.filter_search_button.setToolTip('filter search')
        self.export_button = QtWidgets.QPushButton(self.centralWidget)
        self.export_button.setObjectName("export_button")
        self.export_button.setMinimumSize(40, 40)
        self.export_button.setMaximumSize(40, 40)
        self.export_button.setToolTip('export to csv')
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        horizontal_layout.addWidget(self.add_account_button)
        horizontal_layout.addWidget(self.modify_account_button)
        horizontal_layout.addWidget(self.remove_account_button)
        horizontal_layout.addWidget(self.add_column_button)
        horizontal_layout.addWidget(self.rename_column_button)
        horizontal_layout.addWidget(self.remove_column_button)
        horizontal_layout.addWidget(self.reset_button)
        horizontal_layout.addWidget(self.search_bar)
        horizontal_layout.addWidget(self.filter_search_button)
        horizontal_layout.addWidget(self.export_button)
        vertical_layout.addLayout(horizontal_layout)
        vertical_layout.addWidget(self.tableWidget)
        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password Manager"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Account"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Password"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "URL"))
        self.search_bar.setPlaceholderText(_translate("MainWindow", "Search"))
        self.modify_account_button.setText(_translate("MainWindow", "/A"))
        self.remove_account_button.setText(_translate("MainWindow", "-A"))
        self.add_account_button.setText(_translate("MainWindow", "+A"))
        self.add_column_button.setText(_translate("MainWindow", "+C"))
        self.remove_column_button.setText(_translate("MainWindow", "-C"))
        self.reset_button.setText(_translate("MainWindow", "R"))
        self.rename_column_button.setText(_translate("MainWindow", "/C"))
        self.filter_search_button.setText(_translate("MainWindow", "F"))
        self.export_button.setText(_translate("MainWindow", "E"))
